spring:
    application:
        name: screat_img
    datasource:
        url: jdbc:mariadb://localhost:3306/scrimg
        username: root
        password: 
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MariaDBDialect

    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html

#SSL configuration
server:
    port: 8443
    ssl:
        enabled: true
        key-store: file:/config/keystore.p12
        key-store-password: 
        key-store-type: PKCS12
        key-alias: localhost


